### ISSUE TITLE
Non-byte PyString error during initialisation on Windows in Turkish locale

### ISSUE THREAD

**Issue by kylojsja** [jython/jython#159]
Hi,
Jython 2.7.1 and 2.7.2 
JRE 15 - JRE 16 - JRE 17
I tested but I am getting these error. (same error with 2.7.2)
Jython 2.7.0 it works fine but the last versions I mentioned don't work.

java -jar .\jython-standalone-2.7.1.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.python.core.PyType.init(PyType.java:633)
        at org.python.core.PyType.createType(PyType.java:1523)
        at org.python.core.PyType.addFromClass(PyType.java:1462)
        at org.python.core.PyType.fromClass(PyType.java:1551)
        at org.python.core.PyType.fromClass(PyType.java:1536)
        at org.python.core.PyStringMap.getLazyType(PyStringMap.java:68)
        at org.python.core.PyStringMap.<init>(PyStringMap.java:48)
        at org.python.core.PyStringMap.<init>(PyStringMap.java:44)
        at org.python.expose.BaseTypeBuilder.getDict(BaseTypeBuilder.java:49)
        at org.python.core.PyType.init(PyType.java:621)
        at org.python.core.PyType.addBuilder(PyType.java:1452)
        at org.python.core.PyType.<clinit>(PyType.java)
        at org.python.core.PyObject.<init>(PyObject.java:93)
        at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:22)
        at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
        at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:23)
        at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source)
        at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source)
        at org.python.core.PyDataDescr.<clinit>(PyDataDescr.java)
        at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source)
        at org.python.core.PyBuiltinCallable.<clinit>(PyBuiltinCallable.java)
        at org.python.core.PyObject$PyExposer.<init>(Unknown Source)
        at org.python.core.PyObject.<clinit>(PyObject.java)
        at org.python.util.jython.run(jython.java:241)
        at org.python.util.jython.main(jython.java:142)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.Py.newString(Py.java:647)
        at org.python.core.PyJavaType.init(PyJavaType.java:585)
        at org.python.core.PyType.createType(PyType.java:1523)
        at org.python.core.PyType.addFromClass(PyType.java:1462)
        at org.python.core.PyType.fromClass(PyType.java:1551)
        at org.python.core.PyObject.<init>(PyObject.java:93)
        at org.python.core.PySingleton.<init>(PySingleton.java:9)
        at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
        at org.python.core.Py.<clinit>(Py.java:94)
        ... 25 more 

Best Regards

**Comment by jeff5** [comment]
The only clues here are: `Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value`, and the `\` tells me you are on Windows.

Earlier Jython versions have a unique approach to representing `str` with 16-bit "bytes" that isn't conformant to the Python language. We put that right, but the cost of conformity is the check that produces this message. Unfortunately, parts of the code base still assume characters are 16-bit bytes. We put quite a lot of work into testing, and found many of them, but (it turns out) a few escaped.

Triggers are: non-ascii (or non-latin1) characters in working directories, user names, environment variables. Sometimes the error occurs while attempting to produce a message about something else, encoded for your terminal: if you can, try a simpler code page like 850 or 1252.

I can tell this is somewhere early in initialisation because we are creating the singleton `NotImplemented`. It goes without saying that Jython usually gets further than that. We don't support Jython seriously beyond Java 11, but in practice nearly all the tests pass on 17.

I really wish I'd made that message include the String. (Let's do it: #160.)

**Comment by kylojsja** [comment]
Hi @jeff5 Thanks for response :)
i think I've found out what's causing the problem. if the windows language is not English, this problem occurs. turkish language (special character although it is not, the version does not accept it because the language is Turkish.)  english version 2.7.1 and 2.7.2 for example, I tested on the turkish language windows and these versions did not work, but when I made the windows language english, the latest version of Jython ran smoothly. a strange error.
I hope as in version 2.7.0, special character support is available. because when I tested 2.7.0 with Turkish-language windows, I did not encounter any special character errors.
Best Regards.

**Comment by jeff5** [comment]
That's a useful additional clue. I lately had a fleeting interest in Turkish orthography. However, my simple attempt did not reproduce the problem.
```
PS 159> [console]::OutputEncoding =  [System.Text.Encoding]::GetEncoding(1254)
PS 159> [console]::InputEncoding =  [System.Text.Encoding]::GetEncoding(1254)
PS 159> jython
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_321
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdin.encoding
'cp1254'
>>> sys.stdout.encoding
'cp1254'
>>> print u'\u015eafak'
Şafak
>>> s = u'\u015eafak'.encode('cp1254')
>>> type(s)
<type 'str'>
>>> s
'\xdeafak'
>>> print s
Şafak
>>>
```
It may be I have to localise the PC to Turkish. (Mine is actually localised to Chinese -- but only so I can test Jython.) A work around, if you can formulate it, might benefit others.

**Comment by kylojsja** [comment]
Hi @jeff5  to reproduce the error, you need to make the local language of the computer language Turkish.
then restart the computer (it needs to be in Turkish -> directories and file names), then go to the folder where the latest version of jython is located and try running it with powershell. --> java -jar jython-standalone-2.7.2.jar
you will probably get the same error.

**Comment by jeff5** [comment]
> ... to reproduce the error, you need to make the local language of the computer language Turkish. then restart the computer ... you will probably get the same error.

I localised my PC for Turkish, but was unable to reproduce the error. So I'm not able to trace the bug. The good news is that the difference may be something you can change.

We've had some cases where a user name or file path is the problem but I think we fixed those. I think a non-ascii computer name still can be a problem,

I'm going to make sure that 2.7.3b (in a few weeks I hope) tells you what string it is struggling with and maybe we can fix this for the release.

Here it is working, and a few things I probed looking for trouble:
```
PS C:\Users\Saçlı Meşe\Documents\Jython\gh-iss\159> [console]::OutputEncoding


IsSingleByte      : True
BodyName          : ibm857
EncodingName      : Turkish (DOS)
HeaderName        : ibm857
WebName           : ibm857
WindowsCodePage   : 1254
IsBrowserDisplay  : False
IsBrowserSave     : False
IsMailNewsDisplay : False
IsMailNewsSave    : False
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 857



PS C:\Users\Saçlı Meşe\Documents\Jython\gh-iss\159> java -jar .\jython-standalone-2.7.2.jar                                   Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java17.0.2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, os
>>> sys.stdin.encoding
'cp857'
>>> sys.getfilesystemencoding()
'utf-8'
>>> s = os.environ['USERNAME']
>>> u = s.decode('utf-8')
>>> u
u'Sa\xe7l\u0131 Me\u015fe'
>>>
>>> from java.lang import System
>>> System.getProperty('file.encoding')
u'Cp1254'

```

**Comment by kylojsja** [comment]
Hi @jeff5 I really don't understand what is causing this problem. because Turkish reset the computer and reinstalled it in Turkish, and even if I don't use the turkish name in any way, I still get an error when running jython. Turkish i don't get an error when I use windows in english, but I get an error when I use it in Turkish.
I hope that this error will be fixed in the next version.
Best Regards.

**Comment by jeff5** [comment]
I haven't tried setting the interface language to Turkish: I'm afraid I might never be able to find the way back!

Jython doesn't care what language you're using. But I wonder if somewhere in the works a String pops up from Java or the OS, that is localised, and we assume it will always be ASCII.

> I really don't understand what is causing this problem. 

Nor me. Jython is not giving us much of a clue, hence #160. Going by the stack dump, we try to create a non-byte `str` part way through creating the built-in object `NotImplemented`, here:
https://github.com/jython/jython/blob/4f68d98f34fd6165058944640925b0d1370caf4f/src/org/python/core/PyJavaType.java#L582-L590
AFAICT it's a class name and hard to guess why it would be different for you.

Maybe you'll try the beta with this in when it appears (around Easter #163) and we'll see what that mysterious `String` actually is?

**Comment by kylojsja** [comment]
Hi @jeff5 Thanks for update.
> Jython doesn't care what language you're using.

actually Turkish is important because I have tried it on more than one computer using turkish language (with usernames that are not Turkish characters) but it did not work. i tried running jython 2.7.0 on the same computers and jython 2.7.0 worked successfully. if this was an ascii problem, this version of jython should not work. even turkish characters are not used in the directories here, you can understand that the latest versions of jython are not runed on a computer using the Turkish language.
Strangely enough, the file works when I make the computer language english.
 I hope this issue will be fixed in the latest versions.
Best Regards.

**Comment by jeff5** [comment]
> Hi @jeff5 Thanks for update.
> 
> > Jython doesn't care what language you're using.
> 
> actually Turkish is important 

Of course Turkish is important :) I just mean that if we handle encodings correctly, all languages should be supported equally.

> jython 2.7.0 worked successfully. if this was an ascii problem, this version of jython should not work. 

Not so. In Python 2 `str` means bytes. Jython was unusual in supporting a much wider character set, because our "bytes" were 16-bit. Internally, `str` is represented by Java `String` and so is `unicode`. This is ok within the objects themselves, because you're either in a `PyUnicode` or a `PyString` and know whether to think of the Java String as encoded bytes or decoded characters (in UTF-16). Away from that context, we quickly lose track of which of these things a `String` represents or what the encoding is.

In the interests of a stricter compliance with Python-the-language we had to make bytes the normal size. But `str` kept cropping up with bytes > 255, so we put in a "tell" (for Jython 2.7.1, I think) in the constructor of `PyString`. That found most of the places for us it was happening and we fixed our logic.

Unfortunately, people sometimes find new ones.

**Comment by kylojsja** [comment]
Hi @jeff5 Thanks for response :)
I think jython 2.7.3 (in the new version) will solve this problem, right? I will test it on a computer set to Turkish language.
I hope fixed this problem.

**Comment by xiaoyinl** [comment]
@jeff5 The mysterious `String` is `notımplemented`. The Wikipedia article, [Dotted and dotless I in computing](https://en.wikipedia.org/wiki/Dotted_and_dotless_I_in_computing), explains this exact issue pretty clearly.

Dotted I and dotless I are two letters in Turkish alphabet. Unfortunately, Unicode encodes the uppercase dotless I the same as the English letter I, and the lowercase dotted i the same as English letter i. This can cause confusion, because both Turkish dotless ı and English i have the same uppercase form. Conversely, when you convert uppercase I to its lowercase, the code has to guess if it should be converted to dotless ı or English i. Typically if the locale is Turkish, `ı` is used, while in other locales, `i` is used.

The String here:
https://github.com/jython/jython/blob/87f92b82c51b794bd964f92b6e5b9b83dadb955f/src/org/python/core/PyNotImplemented.java#L10
is converted to its lowercase later. In Turkish locale, it becomes `notımplemented` (non-ASCII), and in all other locales, it becomes `notimplemented`. But I think the code assumes it's always ASCII.

```
C:\Users\...\Desktop\Yeni klasör>java -jar .\jython-standalone.jar
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.python.core.PySystemState.<clinit>(PySystemState.java:80)
        at org.python.util.jython.main(jython.java:593)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value: 'not\u0131mplemented'
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:81)
        at org.python.core.PyString.<init>(PyString.java:85)
        at org.python.core.Py.newString(Py.java:648)
        at org.python.core.PyJavaType.init(PyJavaType.java:543)
        at org.python.core.PyType$Registry.createType(PyType.java:477)
        at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
        at org.python.core.PyType$Registry.resolveType(PyType.java:352)
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at org.python.core.PyType.fromClass(PyType.java:2137)
        at org.python.core.PyObject.<init>(PyObject.java:85)
        at org.python.core.PySingleton.<init>(PySingleton.java:9)
        at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
        at org.python.core.Py.<clinit>(Py.java:64)
        ... 2 more
```

**Comment by jeff5** [comment]
@xiaoyinl : That's brilliant! And unexpected.

In that case, the problem would start here:
https://github.com/jython/jython/blob/87f92b82c51b794bd964f92b6e5b9b83dadb955f/src/org/python/core/PyJavaType.java#L376-L379
The [Javadoc for `String.toLowerCase`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#toLowerCase-java.util.Locale-) makes reference to exactly this issue, and an easy solution.

Although I have set my PC to Turkish, I do not reproduce the problem. But forcing "ROOT" locale here is clearly what we ought to do anyway. (Now I wonder about other case-changing operations ... .)

Yet again. my plan to release v2.7.3b1 is foiled at the last minute.

**Comment by jeff5** [comment]
Possibly a bit hasty closing this since I can't test it where I am. @xiaoyinl can you?

In any case, we will shortly (no really, this time, definitely) have a 2.7.3b1 release with this fix in it, and maybe @kylojsja can install tell us.

**Comment by kylojsja** [comment]
Hi @jeff5 Thanks for update :) 
yes, I can test this. has the beta version been released? I can quickly check it out when it is published.

**Comment by xiaoyinl** [comment]
@jeff5 I confirm this issue is fixed in the latest master 257d6cb.
```
C:\Users\...\Desktop\Yeni klasör>java -jar .\jython-standalone-2.jar
Jython 2.7.3a1-SNAPSHOT (heads/master:257d6cb, Jul 8 2022, 08:32:36)
[OpenJDK 64-Bit Server VM (Microsoft)] on java17.0.3
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by jeff5** [comment]
Excellent. That was worth going round the release process again for. Rolling a beta now.

**Comment by jeff5** [comment]
> Hi @jeff5 Thanks for update :) yes, I can test this. has the beta version been released? I can quickly check it out when it is published.

That would be helpful, @kylojsja . 2.7.3b1 will appear over the weekend, I hope. We run the tests quite a few times in different configurations, and it's about 1h each. Then we'll release via Maven Central.

**Comment by jeff5** [comment]
@kylojsja  Official 2.7.3b1 now up on Sonatype, to be found by: https://search.maven.org/search?q=g:org.python .

I hope this does the trick for you. Let us know!

I plan to announce later today and then give people 4 weeks to find fault. If there's nothing to hold it up, then a quick 2.7.3rc1 will get us to a release in maybe 6 weeks.

**Comment by kylojsja** [comment]
Hi @jeff5 ,
i just checked this out. i can confirm that it has been fixed. thank you for your efforts. ❤️ and @xiaoyinl thank you very much :) 
Best Regards.
